################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/AbstractGraph.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/Graph.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphBelow.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphDots.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphLine.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphPresenter.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphView.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/LegendEntry.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/PainterVerticalAlpha.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/PieChart.cpp 

OBJS += \
./Application/User/Gui/gui/graph_screen/AbstractGraph.o \
./Application/User/Gui/gui/graph_screen/Graph.o \
./Application/User/Gui/gui/graph_screen/GraphBelow.o \
./Application/User/Gui/gui/graph_screen/GraphDots.o \
./Application/User/Gui/gui/graph_screen/GraphLine.o \
./Application/User/Gui/gui/graph_screen/GraphPresenter.o \
./Application/User/Gui/gui/graph_screen/GraphView.o \
./Application/User/Gui/gui/graph_screen/LegendEntry.o \
./Application/User/Gui/gui/graph_screen/PainterVerticalAlpha.o \
./Application/User/Gui/gui/graph_screen/PieChart.o 

CPP_DEPS += \
./Application/User/Gui/gui/graph_screen/AbstractGraph.d \
./Application/User/Gui/gui/graph_screen/Graph.d \
./Application/User/Gui/gui/graph_screen/GraphBelow.d \
./Application/User/Gui/gui/graph_screen/GraphDots.d \
./Application/User/Gui/gui/graph_screen/GraphLine.d \
./Application/User/Gui/gui/graph_screen/GraphPresenter.d \
./Application/User/Gui/gui/graph_screen/GraphView.d \
./Application/User/Gui/gui/graph_screen/LegendEntry.d \
./Application/User/Gui/gui/graph_screen/PainterVerticalAlpha.d \
./Application/User/Gui/gui/graph_screen/PieChart.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Gui/gui/graph_screen/AbstractGraph.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/AbstractGraph.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/Graph.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/Graph.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/GraphBelow.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphBelow.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/GraphDots.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphDots.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/GraphLine.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphLine.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/GraphPresenter.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphPresenter.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/GraphView.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/GraphView.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/LegendEntry.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/LegendEntry.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/PainterVerticalAlpha.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/PainterVerticalAlpha.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/graph_screen/PieChart.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/graph_screen/PieChart.cpp Application/User/Gui/gui/graph_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Gui-2f-gui-2f-graph_screen

clean-Application-2f-User-2f-Gui-2f-gui-2f-graph_screen:
	-$(RM) ./Application/User/Gui/gui/graph_screen/AbstractGraph.cyclo ./Application/User/Gui/gui/graph_screen/AbstractGraph.d ./Application/User/Gui/gui/graph_screen/AbstractGraph.o ./Application/User/Gui/gui/graph_screen/AbstractGraph.su ./Application/User/Gui/gui/graph_screen/Graph.cyclo ./Application/User/Gui/gui/graph_screen/Graph.d ./Application/User/Gui/gui/graph_screen/Graph.o ./Application/User/Gui/gui/graph_screen/Graph.su ./Application/User/Gui/gui/graph_screen/GraphBelow.cyclo ./Application/User/Gui/gui/graph_screen/GraphBelow.d ./Application/User/Gui/gui/graph_screen/GraphBelow.o ./Application/User/Gui/gui/graph_screen/GraphBelow.su ./Application/User/Gui/gui/graph_screen/GraphDots.cyclo ./Application/User/Gui/gui/graph_screen/GraphDots.d ./Application/User/Gui/gui/graph_screen/GraphDots.o ./Application/User/Gui/gui/graph_screen/GraphDots.su ./Application/User/Gui/gui/graph_screen/GraphLine.cyclo ./Application/User/Gui/gui/graph_screen/GraphLine.d ./Application/User/Gui/gui/graph_screen/GraphLine.o ./Application/User/Gui/gui/graph_screen/GraphLine.su ./Application/User/Gui/gui/graph_screen/GraphPresenter.cyclo ./Application/User/Gui/gui/graph_screen/GraphPresenter.d ./Application/User/Gui/gui/graph_screen/GraphPresenter.o ./Application/User/Gui/gui/graph_screen/GraphPresenter.su ./Application/User/Gui/gui/graph_screen/GraphView.cyclo ./Application/User/Gui/gui/graph_screen/GraphView.d ./Application/User/Gui/gui/graph_screen/GraphView.o ./Application/User/Gui/gui/graph_screen/GraphView.su ./Application/User/Gui/gui/graph_screen/LegendEntry.cyclo ./Application/User/Gui/gui/graph_screen/LegendEntry.d ./Application/User/Gui/gui/graph_screen/LegendEntry.o ./Application/User/Gui/gui/graph_screen/LegendEntry.su ./Application/User/Gui/gui/graph_screen/PainterVerticalAlpha.cyclo ./Application/User/Gui/gui/graph_screen/PainterVerticalAlpha.d ./Application/User/Gui/gui/graph_screen/PainterVerticalAlpha.o ./Application/User/Gui/gui/graph_screen/PainterVerticalAlpha.su ./Application/User/Gui/gui/graph_screen/PieChart.cyclo ./Application/User/Gui/gui/graph_screen/PieChart.d ./Application/User/Gui/gui/graph_screen/PieChart.o ./Application/User/Gui/gui/graph_screen/PieChart.su

.PHONY: clean-Application-2f-User-2f-Gui-2f-gui-2f-graph_screen

