################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/CircularProgress.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/CustomControlsPresenter.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/CustomControlsView.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/DatePicker.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/Gauge.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/ThreeWayProgressBar.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/ThreeWayProgressBarCircle.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/VerticalSlideMenu.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/WheelSelector.cpp \
E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/WheelSelectorExtra.cpp 

OBJS += \
./Application/User/Gui/gui/custom_controls_screen/CircularProgress.o \
./Application/User/Gui/gui/custom_controls_screen/CustomControlsPresenter.o \
./Application/User/Gui/gui/custom_controls_screen/CustomControlsView.o \
./Application/User/Gui/gui/custom_controls_screen/DatePicker.o \
./Application/User/Gui/gui/custom_controls_screen/Gauge.o \
./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBar.o \
./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBarCircle.o \
./Application/User/Gui/gui/custom_controls_screen/VerticalSlideMenu.o \
./Application/User/Gui/gui/custom_controls_screen/WheelSelector.o \
./Application/User/Gui/gui/custom_controls_screen/WheelSelectorExtra.o 

CPP_DEPS += \
./Application/User/Gui/gui/custom_controls_screen/CircularProgress.d \
./Application/User/Gui/gui/custom_controls_screen/CustomControlsPresenter.d \
./Application/User/Gui/gui/custom_controls_screen/CustomControlsView.d \
./Application/User/Gui/gui/custom_controls_screen/DatePicker.d \
./Application/User/Gui/gui/custom_controls_screen/Gauge.d \
./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBar.d \
./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBarCircle.d \
./Application/User/Gui/gui/custom_controls_screen/VerticalSlideMenu.d \
./Application/User/Gui/gui/custom_controls_screen/WheelSelector.d \
./Application/User/Gui/gui/custom_controls_screen/WheelSelectorExtra.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Gui/gui/custom_controls_screen/CircularProgress.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/CircularProgress.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/CustomControlsPresenter.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/CustomControlsPresenter.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/CustomControlsView.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/CustomControlsView.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/DatePicker.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/DatePicker.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/Gauge.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/Gauge.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBar.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/ThreeWayProgressBar.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBarCircle.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/ThreeWayProgressBarCircle.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/VerticalSlideMenu.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/VerticalSlideMenu.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/WheelSelector.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/WheelSelector.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Gui/gui/custom_controls_screen/WheelSelectorExtra.o: E:/Sexto_sem/MCU_avanzados/TouchGFX/Gui/gui/src/custom_controls_screen/WheelSelectorExtra.cpp Application/User/Gui/gui/custom_controls_screen/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DST -DSTM32F746xx -DUSE_BPP=16 -DUSE_FLOATING_POINT -c -I../../../Gui/gui/include -I../../../Gui/generated/fonts/include -I../../../Gui/generated/images/include -I../../../Gui/generated/texts/include -I../../../Middlewares/ST/TouchGFX/touchgfx/framework/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32746G-Discovery -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Gui/target -I../../../Core/Inc -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -Wno-strict-aliasing -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Gui-2f-gui-2f-custom_controls_screen

clean-Application-2f-User-2f-Gui-2f-gui-2f-custom_controls_screen:
	-$(RM) ./Application/User/Gui/gui/custom_controls_screen/CircularProgress.cyclo ./Application/User/Gui/gui/custom_controls_screen/CircularProgress.d ./Application/User/Gui/gui/custom_controls_screen/CircularProgress.o ./Application/User/Gui/gui/custom_controls_screen/CircularProgress.su ./Application/User/Gui/gui/custom_controls_screen/CustomControlsPresenter.cyclo ./Application/User/Gui/gui/custom_controls_screen/CustomControlsPresenter.d ./Application/User/Gui/gui/custom_controls_screen/CustomControlsPresenter.o ./Application/User/Gui/gui/custom_controls_screen/CustomControlsPresenter.su ./Application/User/Gui/gui/custom_controls_screen/CustomControlsView.cyclo ./Application/User/Gui/gui/custom_controls_screen/CustomControlsView.d ./Application/User/Gui/gui/custom_controls_screen/CustomControlsView.o ./Application/User/Gui/gui/custom_controls_screen/CustomControlsView.su ./Application/User/Gui/gui/custom_controls_screen/DatePicker.cyclo ./Application/User/Gui/gui/custom_controls_screen/DatePicker.d ./Application/User/Gui/gui/custom_controls_screen/DatePicker.o ./Application/User/Gui/gui/custom_controls_screen/DatePicker.su ./Application/User/Gui/gui/custom_controls_screen/Gauge.cyclo ./Application/User/Gui/gui/custom_controls_screen/Gauge.d ./Application/User/Gui/gui/custom_controls_screen/Gauge.o ./Application/User/Gui/gui/custom_controls_screen/Gauge.su ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBar.cyclo ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBar.d ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBar.o ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBar.su ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBarCircle.cyclo ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBarCircle.d ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBarCircle.o ./Application/User/Gui/gui/custom_controls_screen/ThreeWayProgressBarCircle.su ./Application/User/Gui/gui/custom_controls_screen/VerticalSlideMenu.cyclo ./Application/User/Gui/gui/custom_controls_screen/VerticalSlideMenu.d ./Application/User/Gui/gui/custom_controls_screen/VerticalSlideMenu.o ./Application/User/Gui/gui/custom_controls_screen/VerticalSlideMenu.su ./Application/User/Gui/gui/custom_controls_screen/WheelSelector.cyclo ./Application/User/Gui/gui/custom_controls_screen/WheelSelector.d ./Application/User/Gui/gui/custom_controls_screen/WheelSelector.o ./Application/User/Gui/gui/custom_controls_screen/WheelSelector.su ./Application/User/Gui/gui/custom_controls_screen/WheelSelectorExtra.cyclo ./Application/User/Gui/gui/custom_controls_screen/WheelSelectorExtra.d ./Application/User/Gui/gui/custom_controls_screen/WheelSelectorExtra.o ./Application/User/Gui/gui/custom_controls_screen/WheelSelectorExtra.su

.PHONY: clean-Application-2f-User-2f-Gui-2f-gui-2f-custom_controls_screen

